services:
  server:
    container_name: "recipewebsite_server"
    env_file: .env
    build: ./server
    networks:
      - backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"

  database:
    image: "postgres:latest"
    container_name: "recipewebsite_postgres"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DATABASE: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${DATABASE_HOST}
      PGUSER: ${DATABASE_USER}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    name: recipewebsite_backend_network
    driver: bridge

volumes:
  db-data: