services:
  backend:
    build: RecipeWebsite.Server/
    env_file: "backend.env"
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz"]
      interval: 5s
      retries: 5

  database:
    image: postgres:latest
    env_file: "database.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy