services:
  backend:
    build: RecipeWebsite.Server/
    env_file: "backend.env"
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz"]
      interval: 2s
      retries: 10
    volumes:
      - backend-static-files-volume:/app/static

  database:
    image: postgres:latest
    env_file: "database.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      retries: 10
    volumes:
      - database-volume:/var/lib/postgresql/data/


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy

volumes:
  database-volume:
  backend-static-files-volume: